# Generated by Django 5.0.1 on 2024-01-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor')], max_length=50)),
                ('cargo', models.CharField(blank=True, choices=[('asesor', 'Asesor'), ('cajero', 'Cajero')], max_length=50, null=True)),
                ('longitud', models.FloatField(blank=True, default=0, null=True)),
                ('latitud', models.FloatField(blank=True, default=0, null=True)),
                ('estado_geo', models.CharField(max_length=100)),
            ],
        ),
    ]
