# Generated by Django 5.0.1 on 2024-01-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercreates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo_Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('longitud', models.FloatField(blank=True, default=0, null=True)),
                ('latitud', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_geo',
            field=models.BooleanField(default=False),
        ),
    ]
